REPLACE INTO `role` VALUES (1,'ADMIN');
REPLACE INTO `role` VALUES (2,'USER');
REPLACE INTO `role` VALUES (3,'USER2');
REPLACE INTO `Taveler` VALUES (1,'1986-01-08','Ilia Mahsevitzky');
REPLACE INTO `Taveler` VALUES (2,'1985-08-08','Trav Aller');
