REPLACE INTO `role` VALUES (1,'ADMIN');
REPLACE INTO `role` VALUES (2,'USER');
REPLACE INTO `role` VALUES (3,'USER2');
REPLACE INTO `Taveler` VALUES (2,'1986-12-08','Traveller2');
REPLACE INTO `Taveler` VALUES (3,'1985-08-08','Trav Aller');
